export const COLORS = {
    HOT_CHOCOLATE: '#592E2D',
    GOLD_LEAF: '#A57C55',
    TEAL: '#008080',
    DARK_GREEN: '#004B3A',
    BLACK_COFFEE: '#3B3029',
    NAVY_BLUE: '#2C3E50',
    DARK_GOLDENROD: '#B8860B',
    ALABASTER: '#FAFAFA',
    WHITE: '#FFFFFF',
    BURGUNDY: '#B00020',
    TAN: '#B39B72',
    DARK_GRAY: '#2C2C2C',
    DIM_GRAY: '#696969',
    JET_BLACK: 'rgba(14, 9, 0, 1)',
    CHARCOAL: '#1C1C1C',
};

export const EXPENSE_COLORS = [
    COLORS.HOT_CHOCOLATE, COLORS.GOLD_LEAF, COLORS.TEAL, COLORS.DARK_GREEN, COLORS.BLACK_COFFEE,
    COLORS.NAVY_BLUE, COLORS.DARK_GOLDENROD, COLORS.BURGUNDY, COLORS.TAN, COLORS.DARK_GRAY,
];

export const INVESTMENT_COLORS = [
    COLORS.TAN, COLORS.GOLD_LEAF, COLORS.DARK_GREEN, COLORS.NAVY_BLUE, COLORS.DARK_GRAY,
];
